package com.cbhb.detect.dal.entity;

public class DetectResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detectresult.id
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detectresult.cardnum
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    private String cardnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detectresult.date
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detectresult.message
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detectresult.detecttype
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    private String detecttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detectresult.amt
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    private Integer amt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detectresult.detecttime
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    private String detecttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detectresult.pid
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detectresult.url
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detectresult.id
     *
     * @return the value of detectresult.id
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detectresult.id
     *
     * @param id the value for detectresult.id
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detectresult.cardnum
     *
     * @return the value of detectresult.cardnum
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detectresult.cardnum
     *
     * @param cardnum the value for detectresult.cardnum
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detectresult.date
     *
     * @return the value of detectresult.date
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detectresult.date
     *
     * @param date the value for detectresult.date
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detectresult.message
     *
     * @return the value of detectresult.message
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detectresult.message
     *
     * @param message the value for detectresult.message
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detectresult.detecttype
     *
     * @return the value of detectresult.detecttype
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public String getDetecttype() {
        return detecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detectresult.detecttype
     *
     * @param detecttype the value for detectresult.detecttype
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public void setDetecttype(String detecttype) {
        this.detecttype = detecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detectresult.amt
     *
     * @return the value of detectresult.amt
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public Integer getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detectresult.amt
     *
     * @param amt the value for detectresult.amt
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public void setAmt(Integer amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detectresult.detecttime
     *
     * @return the value of detectresult.detecttime
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public String getDetecttime() {
        return detecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detectresult.detecttime
     *
     * @param detecttime the value for detectresult.detecttime
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public void setDetecttime(String detecttime) {
        this.detecttime = detecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detectresult.pid
     *
     * @return the value of detectresult.pid
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detectresult.pid
     *
     * @param pid the value for detectresult.pid
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detectresult.url
     *
     * @return the value of detectresult.url
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detectresult.url
     *
     * @param url the value for detectresult.url
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}