spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/cbhb/detect/dal/persistence/*Mapper.xml
  type-aliases-package: com.cbhb.detect.dal.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
