package com.cbhb.detect.dal.persistence;

import com.cbhb.detect.dal.entity.DetectResult;
import java.util.List;

public interface DetectResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detectresult
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detectresult
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    int insert(DetectResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detectresult
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    DetectResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detectresult
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    List<DetectResult> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detectresult
     *
     * @mbg.generated Sat Jan 18 12:46:52 CST 2020
     */
    int updateByPrimaryKey(DetectResult record);
}